local: development
remote: staging

#defaults
database_config_file: 'config/database.yml'   # this is the default
backups:
  dir: db_backups
  compress:  gzip   # [ none, gzip, bzip2, 7zip ]
  prefix: backup
  retain:
    periodic:
      hourlies: 1
  frequency: hourly

log:
  target: log/backups.log
  level: warn

production:
  backups:
    retain:
      periodic:
        hourlies:   48
        dailies:    14
        weeklies:   8
      calendar:
        monthlies: 12
        quarterly: all

  database_config_env: production

  user: root
  host: some.server.com
  path: "/var/www/someapp.com/current"
  compress: gzip

staging:
  database_config_env: staging
  path: "/var/www/staging.someapp.com/current"

  user: root
  host: some.server.com

development:
  log:
    target: stderr
  database_config_env: development
  path: "."
  rsa_files:
    staging: "id_rsa"
    production: "id_rsa"
