local: development
remote: staging

#defaults
database_config_file: 'config/database.yml'   # this is the default

production:
  backups:
    dir: db_backups
    compress:  gzip   # [ none, gzip, bzip2, 7zip ]
    keep:
      hourlies:   48
      dailies:    14
      weeklies:   8
      monthlies:  all

    create: hourly
    prune:  daily
    clone:
      storage: s3  [ file, ftp, scp ]
      target: db_backups   # URL

  database_config_env: production

  user: root
  host: some.server.com
  path: "/var/www/someapp.com/current"
  compress: gzip

staging:
  database_config_env: staging
  path: "/var/www/staging.someapp.com/current"

  user: root
  host: some.server.com
  backups:
    compress: gzip

development:
  database_config_env: development
  path: "."
  rsa_files:
    staging: "id_rsa"
    production: "id_rsa"
